config/routes.rb
Rails.application.routes.draw do
resources :cocktails do
    resources :doses, only: [:index, :show, :new, :create]
end
resources :doses
end


# only: [:index :show  :new :create

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, :dependent => :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true


end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  # validates :ingredient, presence: true
  # validates :ingredient, uniqueness: true
  # validates :cocktail, presence: true
  # validates :cocktail, uniqueness: true

  validates_uniqueness_of :ingredient_id, :scope => [:cocktail_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])

  end

  def new
    @cocktail = Cocktail.new
  end

  def create
  #Create a restaurant with attributes from the params
    @cocktail = Cocktail.new(cocktail_params)
  # save it
    if @cocktail.save
  # redirect
      redirect_to cocktail_path(@cocktail)
    else
      render :new #render 'new.html.erb'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

before_action :set_cocktail, only: [:new, :create]

  def index
    @doses = Dose.all
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(doses_params)
    @dose.cocktail = @cocktails
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktail/show'
      end
  end

   private
  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def doses_params
    params.require(:dose).permit(:description)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<h1 class="text-center">All the cocktails</h1>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <h2><%= link_to cocktail.name, cocktail_path(cocktail) %></h2>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

      <h1>Create a new cocktail</h1>
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<h3 class="text-center"> Cocktail name </h3>
<h1 class="text-center"><%= @cocktail.name %></h1>


<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">


      <%= link_to "Back to cocktails", cocktails_path %>
    </div>
  </div>
</div>

app/views/doses/index.html.erb
<h1 class="text-center">All the doses</h1>

<div class="container">
  <div class="row">
    <% @doses.each do |dose| %>
      <div class="col-xs-12 col-sm-4">
        <h2><%= link_to dose.description, cocktail_dose_path(dose) %></h2>
      </div>
    <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Add a ingredient for <%= @cocktail.name %></h1>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
        <%= f.input :description%>
        <%= f.submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>